name: Write version files on semantic tag push

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # only semantic v* tags

permissions:
  contents: write # allow committing back to the repo

jobs:
  write-version-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history (include tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Capture metadata
        id: meta
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          SHA_SHORT="$(git rev-parse --short=7 "$GITHUB_SHA")"
          DATE_UTC="$(date -u +'%Y-%m-%d')"
          ISO_UTC="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
          REPO="${{ github.repository }}"
          RUN_ID="${{ github.run_id }}"
          RUN_NUMBER="${{ github.run_number }}"

          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "sha=$SHA_SHORT" >> "$GITHUB_OUTPUT"
          echo "date=$DATE_UTC" >> "$GITHUB_OUTPUT"
          echo "iso=$ISO_UTC" >> "$GITHUB_OUTPUT"
          echo "default_branch=$DEFAULT_BRANCH" >> "$GITHUB_OUTPUT"
          echo "repo=$REPO" >> "$GITHUB_OUTPUT"
          echo "run_id=$RUN_ID" >> "$GITHUB_OUTPUT"
          echo "run_number=$RUN_NUMBER" >> "$GITHUB_OUTPUT"

      # Ensure the tag’s commit is contained in the default branch
      - name: Check if tag commit is on default branch
        id: check
        shell: bash
        run: |
          git fetch origin "${{ steps.meta.outputs.default_branch }}"
          if git branch --remotes --contains "$GITHUB_SHA" | grep -q "origin/${{ steps.meta.outputs.default_branch }}"; then
            echo "on_default=true" >> "$GITHUB_OUTPUT"
          else
            echo "on_default=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Stop if not on default branch
        if: steps.check.outputs.on_default == 'false'
        run: |
          echo "Tag commit is not on default branch (${{ steps.meta.outputs.default_branch }}). Skipping commit."
          exit 0

      - name: Switch to default branch working tree
        run: |
          git checkout "${{ steps.meta.outputs.default_branch }}"
          git pull --ff-only origin "${{ steps.meta.outputs.default_branch }}"

      - name: Write version.txt and version.json
        shell: bash
        run: |
          echo "${{ steps.meta.outputs.tag }} (${{ steps.meta.outputs.sha }}, ${{ steps.meta.outputs.date }})" > version.txt

          cat > version.json <<'JSON'
          {
            "version": "${{ steps.meta.outputs.tag }}",
            "commit": "${{ steps.meta.outputs.sha }}",
            "date": "${{ steps.meta.outputs.date }}",
            "datetime": "${{ steps.meta.outputs.iso }}",
            "defaultBranch": "${{ steps.meta.outputs.default_branch }}",
            "repository": "${{ steps.meta.outputs.repo }}",
            "run": {
              "id": "${{ steps.meta.outputs.run_id }}",
              "number": "${{ steps.meta.outputs.run_number }}"
            }
          }
          JSON

          echo "== version.txt =="
          cat version.txt
          echo "== version.json =="
          cat version.json
          echo

      - name: Commit and push if changed
        shell: bash
        run: |
          if ! git diff --quiet -- version.txt version.json; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add version.txt version.json
            git commit -m "chore: version files for ${{ steps.meta.outputs.tag }} (${{ steps.meta.outputs.sha }}, ${{ steps.meta.outputs.date }})"
            git push origin "${{ steps.meta.outputs.default_branch }}"
          else
            echo "No changes to version files; nothing to commit."
          fi
